/**
 * Code Review Engine - HTML Reporter
 *
 * Generate HTML format reports.
 */

import type { CodeIssue, ReportOptions, ReviewResult } from "../types.js";

export class HtmlReporter {
	/**
	 * Generate HTML report
	 */
	generate(result: ReviewResult, options: ReportOptions): string {
		return `<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Code Review Report - ${result.id}</title>
	<style>
		* { box-sizing: border-box; margin: 0; padding: 0; }
		body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; background: #f5f5f5; }
		.container { max-width: 1200px; margin: 0 auto; padding: 20px; }
		header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 20px; }
		header h1 { font-size: 2rem; margin-bottom: 10px; }
		header .meta { opacity: 0.9; font-size: 0.9rem; }
		.summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 20px; }
		.summary-card { background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
		.summary-card h3 { font-size: 0.9rem; color: #666; margin-bottom: 5px; }
		.summary-card .value { font-size: 2rem; font-weight: bold; }
		.summary-card.errors .value { color: #e74c3c; }
		.summary-card.warnings .value { color: #f39c12; }
		.summary-card.info .value { color: #3498db; }
		.issues { background: white; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); overflow: hidden; }
		.issue { padding: 15px 20px; border-bottom: 1px solid #eee; }
		.issue:last-child { border-bottom: none; }
		.issue-header { display: flex; align-items: center; gap: 10px; margin-bottom: 10px; }
		.severity-badge { padding: 4px 12px; border-radius: 20px; font-size: 0.75rem; font-weight: bold; text-transform: uppercase; }
		.severity-badge.error { background: #fde8e8; color: #e74c3c; }
		.severity-badge.warning { background: #fef3e2; color: #f39c12; }
		.severity-badge.info { background: #e8f4fd; color: #3498db; }
		.severity-badge.hint { background: #f0f0f0; color: #666; }
		.category { color: #666; font-size: 0.85rem; }
		.issue-title { font-weight: 600; margin-bottom: 5px; }
		.issue-location { color: #888; font-size: 0.85rem; margin-bottom: 10px; }
		.issue-message { color: #555; margin-bottom: 10px; }
		.issue-code { background: #f8f9fa; padding: 10px; border-radius: 5px; font-family: 'Monaco', 'Menlo', monospace; font-size: 0.85rem; overflow-x: auto; }
		.issue-suggestion { background: #e8f5e9; padding: 10px; border-radius: 5px; margin-top: 10px; color: #2e7d32; }
		.empty-state { text-align: center; padding: 60px; color: #666; }
		.empty-state .icon { font-size: 4rem; margin-bottom: 20px; }
		footer { text-align: center; padding: 20px; color: #888; font-size: 0.85rem; }
	</style>
</head>
<body>
	<div class="container">
		<header>
			<h1>Code Review Report</h1>
			<div class="meta">
				<p>Review ID: ${result.id}</p>
				<p>Generated: ${new Date(result.timestamp).toLocaleString()}</p>
				<p>Duration: ${result.durationMs}ms</p>
			</div>
		</header>

		<div class="summary">
			<div class="summary-card">
				<h3>Files Reviewed</h3>
				<div class="value">${result.stats.filesReviewed}</div>
			</div>
			<div class="summary-card">
				<h3>Lines Reviewed</h3>
				<div class="value">${result.stats.linesReviewed}</div>
			</div>
			<div class="summary-card errors">
				<h3>Errors</h3>
				<div class="value">${result.summary.errors}</div>
			</div>
			<div class="summary-card warnings">
				<h3>Warnings</h3>
				<div class="value">${result.summary.warnings}</div>
			</div>
			<div class="summary-card info">
				<h3>Info</h3>
				<div class="value">${result.summary.info}</div>
			</div>
		</div>

		<div class="issues">
			${
				result.issues.length > 0
					? result.issues
							.map((issue) => this.renderIssue(issue, options))
							.join("\n")
					: `
			<div class="empty-state">
				<div class="icon">✓</div>
				<h2>No Issues Found</h2>
				<p>Your code passed all automated checks!</p>
			</div>
			`
			}
		</div>

		<footer>
			<p>Generated by pi-harness-runtime Code Review Engine</p>
		</footer>
	</div>
</body>
</html>`;
	}

	/**
	 * Render a single issue
	 */
	private renderIssue(issue: CodeIssue, options: ReportOptions): string {
		const location = issue.file + (issue.line ? `:${issue.line}` : "");

		return `
		<div class="issue">
			<div class="issue-header">
				<span class="severity-badge ${issue.severity}">${issue.severity}</span>
				<span class="category">${issue.category}</span>
			</div>
			<div class="issue-title">${this.escapeHtml(issue.title)}</div>
			<div class="issue-location">${this.escapeHtml(location)} ${issue.rule ? `• Rule: ${this.escapeHtml(issue.rule)}` : ""}</div>
			<div class="issue-message">${this.escapeHtml(issue.message)}</div>
			${issue.code && options.includeCode !== false ? `<div class="issue-code">${this.escapeHtml(issue.code)}</div>` : ""}
			${issue.suggestion && options.includeSuggestions !== false ? `<div class="issue-suggestion"><strong>Suggestion:</strong> ${this.escapeHtml(issue.suggestion)}</div>` : ""}
		</div>`;
	}

	/**
	 * Escape HTML
	 */
	private escapeHtml(text: string): string {
		return text
			.replace(/&/g, "&amp;")
			.replace(/</g, "&lt;")
			.replace(/>/g, "&gt;")
			.replace(/"/g, "&quot;")
			.replace(/'/g, "&#039;");
	}
}
